version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: WebAPI/Dockerfile
        ports:
            - "5000:8080"
            - "5001:8081"
        depends_on:
            - db
        environment:
            - ConnectionsStrings___DefaultConnection=Server=db;Database=FiftyFiftyDB;User Id=sa;Password=Siemano123!;TrustServerCertificate=True;
        networks:
            - app-network

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: "fifty-fifty-db"
        restart: always
        environment:
            SA_PASSWORD: "Siemano123!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            - app-network
        volumes:
            - db-data:/var/opt/mssql

networks:
    app-network:  
    
volumes:
    db-data: